=== marouaneaba/LABD/tp1/deplacements.dtd
<!ELEMENT  deplacements (trajet ,deplacement,(deplacement|correspondance)*)>
<!ELEMENT  trajet (depart,destination,date,modeTranspore,preference?,vitesseDeMarchePied?,TempParcours)>
<!ELEMENT  depart (#PCDATA)>
<!ELEMENT  destination (#PCDATA)>
<!ELEMENT  date (jour,mois,heur)>
<!ELEMENT  jour (#PCDATA)>
<!ELEMENT  mois (#PCDATA)>
<!ELEMENT  heur (#PCDATA)>
<!ATTLIST jour nom CDATA #REQUIRED
                num CDATA #REQUIRED>
<!ATTLIST  mois nom CDATA #REQUIRED>
<!ATTLIST  heur valeur CDATA #REQUIRED>
<!ELEMENT  modeTranspore (#PCDATA)>
<!ELEMENT preference (#PCDATA)>
<!ELEMENT vitesseDeMarchePied EMPTY>
<!ATTLIST vitesseDeMarchePied valeur CDATA #REQUIRED>
<!ELEMENT TempParcours EMPTY>
<!ATTLIST TempParcours valeur CDATA #REQUIRED>
<!ELEMENT deplacement  (pied|mode)>
<!ATTLIST deplacement heur CDATA #IMPLIED>
<!ELEMENT pied (depart,destination,durée)>
<!ELEMENT durée EMPTY>
<!ATTLIST durée valeur CDATA #REQUIRED>
<!ELEMENT mode (direction,descendre)>
<!ATTLIST mode nom CDATA #REQUIRED
			   ligne CDATA #REQUIRED
			   company CDATA #IMPLIED
			   duree CDATA #REQUIRED>
<!ELEMENT direction (#PCDATA)>
<!ELEMENT descendre (#PCDATA)>
<!ATTLIST descendre heur CDATA #REQUIRED>
<!ELEMENT correspondance EMPTY>
<!ATTLIST correspondance valeur CDATA #REQUIRED>

=== marouaneaba/LABD/tp1/deplacements.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE deplacements SYSTEM "deplacements.dtd">
<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Tue Jan 24 23:47:43 CET 2017 -->

<deplacements>
	<trajet>
		<depart>Seclin  Cnetre Hospitalier </depart>
		<destination> Roubaix - Avenue Motte </destination> 
		<date>
			<jour nom="Mardi" num="22" />
			<mois nom="Janvier" />
			<heur valeur="12h35" />
		</date>
		<modeTranspore> Metro-Tramway-Bus-Car</modeTranspore>
		<preference> Arriver le plus rapide </preference>
		<vitesseDeMarchePied valeur="Normale" />
		<TempParcours valeur="1h 27min" />
	</trajet>
	
	<deplacement>
		<pied > 
			<depart> Seclin  Centre Hospitalier </depart>
			<destination> Arrét Seclin  Hotel de ville </destination>
			<durée valeur="13 min" />
		</pied>
	</deplacement>	
	
	<deplacement heur="14h51">
			<mode nom="Bus" ligne="52" company="Bus Transpole" duree="23 min">
				<direction> Lille  Porte des Postes  </direction>
				<descendre heur="15h14"> arret Lille  CHR B Calmette </descendre>
			</mode>
	</deplacement>	
	
	<correspondance valeur="4 min" />
	
	<deplacement heur="15h18">
		<mode nom="Metro" ligne="1" company="Metro Transpole" duree="3 min">
				<direction> Villeneuve d’Ascq  4 Cantons Grand Stade</direction>
				<descendre heur="15h21"> l’arrêt Lille  Porte des Postes </descendre>
		</mode>
	</deplacement>
		
	<correspondance valeur="6 min" />	
		
	<deplacement heur="15h27">
		<mode nom="Metro" ligne="2" company="Metro Transpole" duree="25 min">
				<direction>  Tourcoing  CH Dro </direction>
				<descendre heur="15h52"> l’arrêt Roubaix  Epeule Montesquieu </descendre>
		</mode>
	</deplacement>
		
	<correspondance valeur="4 min" />	
	
	<deplacement heur="115h56">
			<mode nom="Bus" ligne="52" company="Bus Transpole" duree="9 min">
				<direction> n direction de Roubaix  fraternité  </direction>
				<descendre heur="16h05"> l’arrêt Roubaix  Avenue Motte </descendre>
			</mode>
	</deplacement>	
		
</deplacements>
