=== marouaneaba/LABD/tp1/java/LABD/tp1-ex4/src/tp1/ex4/exercice4.dtd
<!ELEMENT  deplacements (trajet,deplacement)>
<!ELEMENT  deplacement ((pied*,prendre+,descendre+,correspandence*)+)>
<!ELEMENT  pied (depart,destination,date,temp)>
<!ELEMENT  depart (#PCDATA)>
<!ELEMENT  destination (#PCDATA)>
<!ELEMENT  date (jour,mois,hour)>
<!ELEMENT  jour (#PCDATA)>
<!ELEMENT  mois (#PCDATA)>
<!ELEMENT  hour (#PCDATA)>
<!ELEMENT  temp (hour,min)>
<!ELEMENT  min (#PCDATA)>
<!ELEMENT  prendre (transpole,date,temp)>
<!ELEMENT  transpole (mode,ligne,direction)>
<!ELEMENT  mode (#PCDATA)>
<!ELEMENT  ligne (#PCDATA)>
<!ELEMENT  direction (#PCDATA)>
<!ELEMENT  descendre (arret,date)>
<!ELEMENT  arret (#PCDATA)>
<!ELEMENT  correspandence (temp)>
<!ELEMENT  trajet (depart,destination,date,modeTranspole,preference,vitesseDeMarchePied,temp)>
<!ELEMENT  modeTranspole (#PCDATA)>
<!ELEMENT  preference (#PCDATA)>
<!ELEMENT  vitesseDeMarchePied (#PCDATA)>

=== marouaneaba/LABD/tp1/java/LABD/tp1-ex4/src/tp1/ex4/exercice4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deplacements SYSTEM "exercice4.dtd">

<deplacements>
	<trajet>

		<depart> Seclin - Cnetre Hospitalier </depart>
		<destination> Roubaix - Avenue Motte </destination> 
		<date>
			<jour> Mardi 22 </jour>
			<mois> Janvier </mois>
			<hour> 12h35 </hour>
		</date>
		<modeTranspole> Metro-Tramway-Bus-Car</modeTranspole>
		<preference> Arriver le plus rapide </preference>


		<vitesseDeMarchePied> Normale </vitesseDeMarchePied>
		<temp> 
			<hour> 1 </hour>
			<min> 27 </min>
		</temp>

	</trajet>

	<deplacement>
		<pied> 
			<depart> Seclin - Centre Hospitalier </depart>
			<destination> Arr√©t Seclin - Hotel de ville </destination>
			<date>
				<jour> Mardi 22 </jour>
				<mois> Janvier </mois>
				<hour> 12h35 </hour>
			</date>
			<temp> 
				<hour> 0 </hour>
				<min> 13 </min>
			</temp>
		</pied>
		
		<prendre> 
			<transpole>  
				<mode> Bus </mode>
				<ligne> 52 </ligne>
				<direction> Lille - Porte des Postes  </direction>
			</transpole>
			<date>
				<jour> Mardi 22 </jour>
				<mois> Janvier </mois>
				<hour> 14h51 </hour>
			</date>
			<temp> 
				<hour> 0 </hour>
				<min> 23 </min>
			</temp>	
		</prendre>
		
		<descendre>  
			<arret> Lille - CHR B Calmette </arret>
			<date>
				<jour> Mardi 22 </jour>
				<mois> Janvier </mois>
				<hour> 15h14 </hour>
			</date>
		</descendre>
		
		<correspandence> 
			<temp> 
					<hour> 0 </hour>
					<min> 4 </min>
			</temp>				
		</correspandence>
		
		<prendre> 
			<transpole>  
				<mode> metro </mode>
				<ligne> 1 </ligne>
				<direction> Villeneuve d'asq - 4 Contons Grand Stade </direction>
			</transpole>
			<date>
				<jour> Mardi 22 </jour>
				<mois> Janvier </mois>
				<hour> 15h18 </hour>
			</date>
			<temp> 
				<hour> 0 </hour>
				<min> 3 </min>
			</temp>	
		</prendre>
		
		<descendre>  
			<arret> Lille - Porte des Postes </arret>
			<date>
				<jour> Mardi 22 </jour>
				<mois> Janvier </mois>
				<hour> 15h21 </hour>
			</date>
		</descendre>
		
		<correspandence> 
			<temp> 
					<hour> 0 </hour>
					<min> 6 </min>
			</temp>				
		</correspandence>
		
		<prendre> 
			<transpole>  
				<mode> metro </mode>
				<ligne> 2 </ligne>
				<direction> Tourcoing - CH Dron </direction>
			</transpole>
			<date>
				<jour> Mardi 22 </jour>
				<mois> Janvier </mois>
				<hour> 15h27 </hour>
			</date>
			<temp> 
				<hour> 0 </hour>
				<min> 25 </min>
			</temp>	
		</prendre>
		
		<descendre>  
			<arret> Roubaix - Epeule Montesquieu </arret>
			<date>
				<jour> Mardi 22 </jour>
				<mois> Janvier </mois>
				<hour> 15h52 </hour>
			</date>
		</descendre>
		
		<correspandence> 
			<temp> 
					<hour> 0 </hour>
					<min> 4 </min>
			</temp>				
		</correspandence>
		
		<prendre> 
			<transpole>  
				<mode> Bus </mode>
				<ligne> 25 </ligne>
				<direction> Roubaix - fraternite </direction>
			</transpole>
			<date>
				<jour> Mardi 22 </jour>
				<mois> Janvier </mois>
				<hour> 15h56 </hour>
			</date>
			<temp> 
				<hour> 0 </hour>
				<min> 9 </min>
			</temp>	
		</prendre>
		
		<descendre>  
			<arret> Roubaix - Avenue Motte </arret>
			<date>
				<jour> Mardi 22 </jour>
				<mois> Janvier </mois>
				<hour> 16h05 </hour>
			</date>
		</descendre>
	</deplacement>
	
	
</deplacements>
